<?php

namespace WorkBundle\Repository;
use WorkBundle\Entity\Blacklist;
use WorkBundle\Repository\BlacklistRepository;
/**
 * BlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlacklistRepository extends \Doctrine\ORM\EntityRepository
{
    public function blackToken($token)
    {       
            $em = $this->getEntityManager();        
            $blackObject = new Blacklist;        
            $blackObject->setToken($token);        
            $em->persist($blackObject);        
            $em->flush();
    }
    public function isBlack($token)
    {        
        return $black = $this->findOneBy(["token" => $token]);  
    }
}
