<?php

namespace WorkBundle\Repository;
use Doctrine\ORM\EntityRepository;
use WorkBundle\Entity\Position;
/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function createPosition($application,$jobTitle,$companyName,$address,$reason
    ,$responsibilities,$supervisor,$startSalary,$endSalary,$fromDate,$toDate,$callSupervisor)
    {
        $position = new Position();

        $position->setApplication($application)->setJobTitle($jobTitle)
                 ->setCompanyName($companyName)->setAddress($address)
                 ->setReason($reason)->setResponsibilities($responsibilities)
                 ->setSupervisor($supervisor)->setStartingSalary($startSalary)
                 ->setEndingSalary($endSalary)->setFromDate($fromDate)
                 ->setToDate($toDate)->setCallSupervisor($callSupervisor);

        $em = $this->getEntityManager();
        $em->persist($position);
        $em->flush();
        
        return $position;
    }

    public function deletePosition($positionId)
    {
        $this->createQueryBuilder('a')
             ->delete()
             ->where('a.id =:positionId')
             ->setParameter('positionId',$positionId)
             ->getQuery()
             ->execute();
    }
}
