<?php

namespace WorkBundle\Repository;

/**
 * positionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class positionRepository extends \Doctrine\ORM\EntityRepository
{
}
