<?php

namespace Project\WorkBundle\Repository;

/**
 * degreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class degreeRepository extends \Doctrine\ORM\EntityRepository
{
}
