# app/config/routing.yml
gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
# ...
work:
    resource: "@WorkBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check
    
api_test:
    path: /api/test
    defaults:  { _controller: WorkBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

revoke_token:   
    path: /api/logout    
    defaults: { _controller: WorkBundle:Application:logout}
    methods: [POST]


captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
