# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

        
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:      ROLE_ADMIN
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    admin: 
                      password: admin 
                      roles: 'ROLE_ADMIN'
#        custom_provider:
#            entity:
#                class: WorkBundle:User
#                property: username
#                property: password
    # ...
    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: in_memory
            form_login:
                check_path:               /api/login_check
                username_parameter:       _username 
                password_parameter:       _password 
                success_handler:          lexik_jwt_authentication.handler.authentication_success   
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                
        register:
            pattern:  ^/api/register
            stateless: true
            anonymous: true
            
        api:        
            pattern:   ^/api
            provider: in_memory
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - app.jwt_token_authenticator
                    # - lexik_jwt_authentication.jwt_token_authenticator
 
        
        refresh:
            pattern:  ^/api/token/refresh
            provider: in_memory
            stateless: true
            anonymous: true

    # ...
        main:
            pattern: ^/
            form_login:
#                provider: in_memory
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true   
            
            
    access_control:
          # ...
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/applicant/[1-9]+/edit$, role: ROLE_USER }
        - { path: ^/applicant/[1-9]+/delete$, role: ROLE_ADMIN }
          # ...