WorkBundle\Entity\Blacklist:
    type: entity
    table: null
    repositoryClass: WorkBundle\Repository\BlacklistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            length: 800
            unique: true
        created_at:
            type: datetime
            
    lifecycleCallbacks: 
        prePersist: [ setTimeStamps ]
