WorkBundle\Entity\Education:
    type: entity
     # ...
    oneToOne:
        Application:
            targetEntity: Application
            inversedBy: Education
            joinColumn:
                name: application_id
                referencedColName: id
    table: null
    repositoryClass: WorkBundle\Repository\EducationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        school_name:
            type: string
            length: 255
        school_from:
            type: date
        school_to:
            type: date
        school_degree:
            type: string
            length: 255
        college_name:
            type: string
            length: 255
        college_from: 
            type: string
            length: 255
        college_to:
            type: string
            length: 255
        is_graduate:
            type: boolean
        graduate_degree:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
