WorkBundle\Entity\Employee:
    type: entity
    # ...
#    oneToOne:
#        Application:
#            targetEntity: Application
#            inversedBy: Employee
#            fetch: LAZY
#            joinColumn:
#                name: application_id
#                referencedColName: id
    table: null
    repositoryClass: WorkBundle\Repository\EmployeeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nameArabic:
            type: string
            length: 255
            column: name_arabic
        nameEnglish:
            type: string
            length: 255
            column: name_english
        birthDate:
            type: date
            column: birth_date
        address:
            type: string
            length: 255
        homePhone:
            type: string
            length: 255
            nullable: true
            unique: true
            column: home_phone
        mobilePhone:
            type: string
            length: 255
            unique: true
            column: mobile_phone
        emergencyContactPerson:
            type: string
            length: 255
            column: emergency_contact_person
        emergencyPersonNumber:
            type: string
            length: 255
            unique: true
            column: emergency_person_number
        emailPersonal:
            type: string
            length: 255
            unique: true
            column: email_personal
        idCardNumber:
            type: string
            length: 255
            unique: true
            column: id_card_number
        academicDegree:
            type: string
            length: 255
            column: academic_degree
        graduationDate:
            type: date
            column: graduation_date
        joiningDate:
            type: date
            column: joining_date
        currentPosition:
            type: string
            length: 255
            column: current_position
    lifecycleCallbacks: {  }
