# src/AppBundle/Resources/config/doctrine/User.orm.yml
WorkBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO