applicat_index:
    path:     /
    defaults: { _controller: "WorkBundle:Application:index" }
    methods:  GET

applicat_show:
    path:     /{id}/show
    defaults: { _controller: "WorkBundle:Application:show" }
    methods:  GET

applicat_edit:
    path:     /{id}/edit
    defaults: { _controller: "WorkBundle:Application:edit" }
    methods:  [GET, POST]

applicat_delete:
    path:     /{id}/delete
    defaults: { _controller: "WorkBundle:Application:delete" }
    methods:  DELETE

thank_you:
    path:     /thank_you
    defaults: { _controller: "WorkBundle:Default:thank" }
    methods:  GET
