work_applicat:
    resource: "@WorkBundle/Resources/config/routing/application.yml"
    prefix:   /applicant

work_homepage:
    path:     /
    defaults: { _controller: WorkBundle:Default:index }

list:
    path:     /applicant
    defaults: { _controller: WorkBundle:Application:index }

index:
    path:     /try
    defaults: { _controller: WorkBundle:Application:test }
